### ISSUE TITLE
vertical size of the windows

### ISSUE THREAD

**Issue by acapet** [fricour/Shiny-python#2]
Would it be possible to have larger (or dynamic) size of the "windows" for the time series ? 

My issue is that when I have to consider a large number of variables, these becomes very small on the vertical 

![image](https://github.com/user-attachments/assets/e056e3e7-3905-4633-bbbd-93475cc43a56)

I've seen a lower limit to the size of the axes/subplots, but I think the size of the window that is limiting here ...

**Comment by fricour** [comment]
A bit tricky but done.
